import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Static Page",
  description: "Generated by create next app",
};

const StaticRenderingPage = () => {
  return (
    <div>
      <h1>StaticRenderingPage</h1>
      {new Date().toTimeString()}
    </div>
  );
};

export default StaticRenderingPage;
